# Generated by Django 4.2.7 on 2023-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenda",
            name="horario",
        ),
        migrations.AlterField(
            model_name="agenda",
            name="data",
            field=models.DateTimeField(),
        ),
    ]
