# Generated by Django 4.2.7 on 2023-11-26 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agenda", "0002_remove_agenda_horario_alter_agenda_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
