# Generated by Django 4.2.7 on 2023-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_alter_agenda_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="horario",
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agenda",
            name="data",
            field=models.DateField(),
        ),
    ]
