# Generated by Django 4.2.7 on 2023-11-26 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_rename_nome_usuario_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="senha",
            new_name="password",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
    ]
