# Generated by Django 4.2.7 on 2023-11-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
