# Generated by Django 4.2.7 on 2023-11-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_delete_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='preço',
            new_name='preco',
        ),
    ]
