# Generated by Django 4.2.7 on 2023-11-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0004_rename_preço_servico_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='sobrenome',
            field=models.CharField(default='...', max_length=30),
            preserve_default=False,
        ),
    ]
