# Generated by Django 4.2.7 on 2023-11-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barbearia", "0005_barbeiro_sobrenome"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbeiro",
            name="username",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
    ]
